# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main.ui'
##
## Created by: Qt User Interface Compiler version 6.6.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QLabel,
    QMainWindow, QMenu, QMenuBar, QPushButton,
    QSlider, QSizePolicy, QSpinBox, QStatusBar, QSlider,
    QWidget)

class Ui_UIMainWindow(object):
    def setupUi(self, UIMainWindow):
        if not UIMainWindow.objectName():
            UIMainWindow.setObjectName(u"UIMainWindow")
        UIMainWindow.resize(800, 380)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(UIMainWindow.sizePolicy().hasHeightForWidth())
        UIMainWindow.setSizePolicy(sizePolicy)
        UIMainWindow.setMinimumSize(QSize(800, 380))
        UIMainWindow.setMaximumSize(QSize(800, 380))
        UIMainWindow.setFocusPolicy(Qt.NoFocus)
        UIMainWindow.setLocale(QLocale(QLocale.English, QLocale.UnitedKingdom))
        self.actionSettings = QAction(UIMainWindow)
        self.actionSettings.setObjectName(u"actionSettings")
        self.actionQuit = QAction(UIMainWindow)
        self.actionQuit.setObjectName(u"actionQuit")
        icon = QIcon(QIcon.fromTheme(u"QIcon::ThemeIcon::ApplicationExit"))
        self.actionQuit.setIcon(icon)
        self.actionImport = QAction(UIMainWindow)
        self.actionImport.setObjectName(u"actionImport")
        icon1 = QIcon(QIcon.fromTheme(u"QIcon::ThemeIcon::DocumentOpen"))
        self.actionImport.setIcon(icon1)
        self.actionBufferExport = QAction(UIMainWindow)
        self.actionBufferExport.setObjectName(u"actionBufferExport")
        icon5 = QIcon(QIcon.fromTheme(u"QIcon::ThemeIcon::MailAttachment"))
        self.actionBufferExport.setIcon(icon5)
        self.actionBankExport = QAction(UIMainWindow)
        self.actionBankExport.setObjectName(u"actionBankExport")
        icon2 = QIcon(QIcon.fromTheme(u"QIcon::ThemeIcon::DocumentSaveAs"))
        self.actionBankExport.setIcon(icon2)
        self.actionBankSave = QAction(UIMainWindow)
        self.actionBankSave.setObjectName(u"actionBankSave")
        icon3 = QIcon(QIcon.fromTheme(u"QIcon::ThemeIcon::DocumentSave"))
        self.actionBankSave.setIcon(icon3)
        self.actionAbout = QAction(UIMainWindow)
        self.actionAbout.setObjectName(u"actionAbout")
        icon4 = QIcon(QIcon.fromTheme(u"QIcon::ThemeIcon::HelpAbout"))
        self.actionAbout.setIcon(icon4)
        self.actionNew = QAction(UIMainWindow)
        self.actionNew.setObjectName(u"actionNew")
        icon6 = QIcon(QIcon.fromTheme(u"QIcon::ThemeIcon::DocumentNew"))
        self.actionNew.setIcon(icon6)
        self.actionStoreProgram = QAction(UIMainWindow)
        self.actionStoreProgram.setObjectName(u"actionStoreProgram")
        icon7 = QIcon(QIcon.fromTheme(u"QIcon::ThemeIcon::GoNext"))
        self.actionStoreProgram.setIcon(icon7)
        self.actionDeviceStoreBank = QAction(UIMainWindow)
        self.actionDeviceStoreBank.setObjectName(u"actionDeviceStoreBank")
        self.actionDeviceStoreBank.setIcon(icon7)
        self.actionHelp = QAction(UIMainWindow)
        self.actionHelp.setObjectName(u"actionHelp")
        icon8 = QIcon(QIcon.fromTheme(u"QIcon::ThemeIcon::DialogQuestion"))
        self.actionHelp.setIcon(icon8)
        self.actionDeviceRequestBank = QAction(UIMainWindow)
        self.actionDeviceRequestBank.setObjectName(u"actionDeviceRequestBank")
        self.centralwidget = QWidget(UIMainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.CONFIGURATION = QComboBox(self.centralwidget)
        self.CONFIGURATION.addItem("")
        self.CONFIGURATION.addItem("")
        self.CONFIGURATION.addItem("")
        self.CONFIGURATION.addItem("")
        self.CONFIGURATION.addItem("")
        self.CONFIGURATION.addItem("")
        self.CONFIGURATION.addItem("")
        self.CONFIGURATION.addItem("")
        self.CONFIGURATION.addItem("")
        self.CONFIGURATION.addItem("")
        self.CONFIGURATION.addItem("")
        self.CONFIGURATION.addItem("")
        self.CONFIGURATION.addItem("")
        self.CONFIGURATION.addItem("")
        self.CONFIGURATION.addItem("")
        self.CONFIGURATION.setObjectName(u"CONFIGURATION")
        self.CONFIGURATION.setGeometry(QRect(90, 220, 331, 32))
        self.CONFIGURATION.setTabletTracking(True)
        self.CONFIGURATION.setFocusPolicy(Qt.ClickFocus)
        self.CONFIGURATION.setLocale(QLocale(QLocale.English, QLocale.UnitedKingdom))
        self.CHRS_TYPE = QComboBox(self.centralwidget)
        self.CHRS_TYPE.addItem("")
        self.CHRS_TYPE.addItem("")
        self.CHRS_TYPE.addItem("")
        self.CHRS_TYPE.addItem("")
        self.CHRS_TYPE.addItem("")
        self.CHRS_TYPE.addItem("")
        self.CHRS_TYPE.addItem("")
        self.CHRS_TYPE.addItem("")
        self.CHRS_TYPE.addItem("")
        self.CHRS_TYPE.addItem("")
        self.CHRS_TYPE.addItem("")
        self.CHRS_TYPE.addItem("")
        self.CHRS_TYPE.setObjectName(u"CHRS_TYPE")
        self.CHRS_TYPE.setGeometry(QRect(100, 70, 141, 32))
        self.CHRS_TYPE.setTabletTracking(True)
        self.CHRS_TYPE.setFocusPolicy(Qt.ClickFocus)
        self.CHRS_TYPE.setLocale(QLocale(QLocale.English, QLocale.UnitedKingdom))
        self.CHRS_STEREO = QCheckBox(self.centralwidget)
        self.CHRS_STEREO.setObjectName(u"CHRS_STEREO")
        self.CHRS_STEREO.setGeometry(QRect(130, 110, 85, 20))
        self.CHRS_STEREO.setTabletTracking(True)
        self.CHRS_STEREO.setFocusPolicy(Qt.NoFocus)
        self.CHRS_STEREO.setLocale(QLocale(QLocale.English, QLocale.UnitedKingdom))
        self.DLY_TIME_T = QLabel(self.centralwidget)
        self.DLY_TIME_T.setObjectName(u"DLY_TIME_T")
        self.DLY_TIME_T.setGeometry(QRect(260, 180, 51, 31))
        self.DLY_TIME_T.setFocusPolicy(Qt.NoFocus)
        self.DLY_TIME_T.setLocale(QLocale(QLocale.English, QLocale.UnitedKingdom))
        self.DLY_TIME_T.setAlignment(Qt.AlignCenter)
        self.DLY_TIME_T.setWordWrap(True)
        self.DLY_TIME = QSlider(self.centralwidget)
        self.DLY_TIME.setObjectName(u"DLY_TIME")
        self.DLY_TIME.setGeometry(QRect(280, 70, 10, 101))
        self.DLY_TIME.setTabletTracking(True)
        self.DLY_TIME.setFocusPolicy(Qt.ClickFocus)
        self.DLY_TIME.setLocale(QLocale(QLocale.English, QLocale.UnitedKingdom))
        self.DLY_TIME.setMinimum(1)
        self.DLY_TIME.setMaximum(100)
        self.DLY_TIME.setOrientation(Qt.Vertical)
        self.DLY_TIME.setInvertedAppearance(False)
        self.DLY_TIME.setInvertedControls(False)
        self.DLY_TIME_L = QLabel(self.centralwidget)
        self.DLY_TIME_L.setObjectName(u"DLY_TIME_L")
        self.DLY_TIME_L.setGeometry(QRect(250, 50, 71, 16))
        self.DLY_TIME_L.setFocusPolicy(Qt.NoFocus)
        self.DLY_TIME_L.setLocale(QLocale(QLocale.English, QLocale.UnitedKingdom))
        self.DLY_TIME_L.setAlignment(Qt.AlignCenter)
        self.REV_MIX_T = QLabel(self.centralwidget)
        self.REV_MIX_T.setObjectName(u"REV_MIX_T")
        self.REV_MIX_T.setGeometry(QRect(560, 180, 51, 31))
        # self.REV_MIX_T.setGeometry(QRect(500, 180, 51, 31))
        self.REV_MIX_T.setFocusPolicy(Qt.NoFocus)
        self.REV_MIX_T.setLocale(QLocale(QLocale.English, QLocale.UnitedKingdom))
        self.REV_MIX_T.setAlignment(Qt.AlignCenter)
        self.REV_MIX_T.setWordWrap(True)
        self.REV_MIX_L = QLabel(self.centralwidget)
        self.REV_MIX_L.setObjectName(u"REV_MIX_L")
        self.REV_MIX_L.setGeometry(QRect(550, 50, 71, 16))
        # self.REV_MIX_L.setGeometry(QRect(490, 50, 71, 16))
        self.REV_MIX_L.setFocusPolicy(Qt.NoFocus)
        self.REV_MIX_L.setLocale(QLocale(QLocale.English, QLocale.UnitedKingdom))
        self.REV_MIX_L.setAlignment(Qt.AlignCenter)
        self.REV_MIX = QSlider(self.centralwidget)
        self.REV_MIX.setObjectName(u"REV_MIX")
        self.REV_MIX.setGeometry(QRect(580, 70, 10, 101))
        # self.REV_MIX.setGeometry(QRect(520, 70, 10, 101))
        self.REV_MIX.setTabletTracking(True)
        self.REV_MIX.setFocusPolicy(Qt.ClickFocus)
        self.REV_MIX.setLocale(QLocale(QLocale.English, QLocale.UnitedKingdom))
        self.REV_MIX.setMinimum(0)
        self.REV_MIX.setMaximum(99)
        self.REV_MIX.setSliderPosition(0)
        self.REV_MIX.setOrientation(Qt.Vertical)
        self.REV_MIX.setInvertedAppearance(False)
        self.REV_MIX.setInvertedControls(False)
        self.DLY_REGEN_L = QLabel(self.centralwidget)
        self.DLY_REGEN_L.setObjectName(u"DLY_REGEN_L")
        self.DLY_REGEN_L.setGeometry(QRect(310, 50, 71, 16))
        self.DLY_REGEN_L.setFocusPolicy(Qt.NoFocus)
        self.DLY_REGEN_L.setLocale(QLocale(QLocale.English, QLocale.UnitedKingdom))
        self.DLY_REGEN_L.setAlignment(Qt.AlignCenter)
        self.DLY_REGEN_T = QLabel(self.centralwidget)
        self.DLY_REGEN_T.setObjectName(u"DLY_REGEN_T")
        self.DLY_REGEN_T.setGeometry(QRect(320, 180, 51, 31))
        self.DLY_REGEN_T.setFocusPolicy(Qt.NoFocus)
        self.DLY_REGEN_T.setLocale(QLocale(QLocale.English, QLocale.UnitedKingdom))
        self.DLY_REGEN_T.setAlignment(Qt.AlignCenter)
        self.DLY_REGEN_T.setWordWrap(True)
        self.DLY_REGEN = QSlider(self.centralwidget)
        self.DLY_REGEN.setObjectName(u"DLY_REGEN")
        self.DLY_REGEN.setGeometry(QRect(340, 70, 10, 101))
        self.DLY_REGEN.setTabletTracking(True)
        self.DLY_REGEN.setFocusPolicy(Qt.ClickFocus)
        self.DLY_REGEN.setLocale(QLocale(QLocale.English, QLocale.UnitedKingdom))
        self.DLY_REGEN.setMinimum(0)
        self.DLY_REGEN.setMaximum(99)
        self.DLY_REGEN.setOrientation(Qt.Vertical)
        self.DLY_REGEN.setInvertedAppearance(False)
        self.DLY_REGEN.setInvertedControls(False)
        self.REV_DECAY_L = QLabel(self.centralwidget)
        self.REV_DECAY_L.setObjectName(u"REV_DECAY_L")
        self.REV_DECAY_L.setGeometry(QRect(430, 50, 71, 16))
        self.REV_DECAY_L.setFocusPolicy(Qt.NoFocus)
        self.REV_DECAY_L.setLocale(QLocale(QLocale.English, QLocale.UnitedKingdom))
        self.REV_DECAY_L.setAlignment(Qt.AlignCenter)
        self.REV_DECAY = QSlider(self.centralwidget)
        self.REV_DECAY.setObjectName(u"REV_DECAY")
        self.REV_DECAY.setGeometry(QRect(460, 70, 10, 101))
        # self.REV_DECAY.setTabletTracking(True)
        self.REV_DECAY.setFocusPolicy(Qt.ClickFocus)
        self.REV_DECAY.setLocale(QLocale(QLocale.English, QLocale.UnitedKingdom))
        self.REV_DECAY.setMinimum(0)
        self.REV_DECAY.setMaximum(99)
        self.REV_DECAY.setOrientation(Qt.Vertical)
        # self.REV_DECAY.setInvertedAppearance(False)
        # self.REV_DECAY.setInvertedControls(False)
        self.REV_DECAY_T = QLabel(self.centralwidget)
        self.REV_DECAY_T.setObjectName(u"REV_DECAY_T")
        self.REV_DECAY_T.setGeometry(QRect(440, 180, 51, 31))
        self.REV_DECAY_T.setFocusPolicy(Qt.NoFocus)
        self.REV_DECAY_T.setLocale(QLocale(QLocale.English, QLocale.UnitedKingdom))
        self.REV_DECAY_T.setAlignment(Qt.AlignCenter)
        self.REV_DECAY_T.setWordWrap(True)
        self.DLY_MIX_T = QLabel(self.centralwidget)
        self.DLY_MIX_T.setObjectName(u"DLY_MIX_T")
        self.DLY_MIX_T.setGeometry(QRect(380, 175, 51, 41))
        self.DLY_MIX_T.setFocusPolicy(Qt.NoFocus)
        self.DLY_MIX_T.setLocale(QLocale(QLocale.English, QLocale.UnitedKingdom))
        self.DLY_MIX_T.setAlignment(Qt.AlignCenter)
        self.DLY_MIX_T.setWordWrap(True)
        self.DLY_MIX_L = QLabel(self.centralwidget)
        self.DLY_MIX_L.setObjectName(u"DLY_MIX_L")
        self.DLY_MIX_L.setGeometry(QRect(370, 50, 71, 16))
        self.DLY_MIX_L.setFocusPolicy(Qt.NoFocus)
        self.DLY_MIX_L.setLocale(QLocale(QLocale.English, QLocale.UnitedKingdom))
        self.DLY_MIX_L.setAlignment(Qt.AlignCenter)
        self.DLY_MIX = QSlider(self.centralwidget)
        self.DLY_MIX.setObjectName(u"DLY_MIX")
        self.DLY_MIX.setGeometry(QRect(400, 70, 10, 101))
        self.DLY_MIX.setTabletTracking(True)
        self.DLY_MIX.setFocusPolicy(Qt.ClickFocus)
        self.DLY_MIX.setLocale(QLocale(QLocale.English, QLocale.UnitedKingdom))
        self.DLY_MIX.setMinimum(0)
        self.DLY_MIX.setMaximum(99)
        self.DLY_MIX.setOrientation(Qt.Vertical)
        self.DLY_MIX.setInvertedAppearance(False)
        self.DLY_MIX.setInvertedControls(False)
        self.REVERB_TYPE = QComboBox(self.centralwidget)
        self.REVERB_TYPE.addItem("")
        self.REVERB_TYPE.addItem("")
        self.REVERB_TYPE.addItem("")
        self.REVERB_TYPE.addItem("")
        self.REVERB_TYPE.addItem("")
        self.REVERB_TYPE.addItem("")
        self.REVERB_TYPE.addItem("")
        self.REVERB_TYPE.addItem("")
        self.REVERB_TYPE.addItem("")
        self.REVERB_TYPE.addItem("")
        self.REVERB_TYPE.addItem("")
        self.REVERB_TYPE.addItem("")
        self.REVERB_TYPE.addItem("")
        self.REVERB_TYPE.addItem("")
        self.REVERB_TYPE.addItem("")
        self.REVERB_TYPE.addItem("")
        self.REVERB_TYPE.addItem("")
        self.REVERB_TYPE.addItem("")
        self.REVERB_TYPE.addItem("")
        self.REVERB_TYPE.addItem("")
        self.REVERB_TYPE.setObjectName(u"REVERB_TYPE")
        self.REVERB_TYPE.setGeometry(QRect(530, 220, 201, 32))
        self.REVERB_TYPE.setTabletTracking(True)
        self.REVERB_TYPE.setFocusPolicy(Qt.ClickFocus)
        self.REVERB_TYPE.setLocale(QLocale(QLocale.English, QLocale.UnitedKingdom))
        self.IN_EQ_T = QLabel(self.centralwidget)
        self.IN_EQ_T.setObjectName(u"IN_EQ_T")
        self.IN_EQ_T.setGeometry(QRect(30, 180, 51, 31))
        self.IN_EQ_T.setFocusPolicy(Qt.NoFocus)
        self.IN_EQ_T.setLocale(QLocale(QLocale.English, QLocale.UnitedKingdom))
        self.IN_EQ_T.setAlignment(Qt.AlignCenter)
        self.IN_EQ_T.setWordWrap(True)
        self.IN_EQ_L = QLabel(self.centralwidget)
        self.IN_EQ_L.setObjectName(u"IN_EQ_L")
        self.IN_EQ_L.setGeometry(QRect(20, 50, 71, 16))
        self.IN_EQ_L.setFocusPolicy(Qt.NoFocus)
        self.IN_EQ_L.setLocale(QLocale(QLocale.English, QLocale.UnitedKingdom))
        self.IN_EQ_L.setAlignment(Qt.AlignCenter)
        self.IN_EQ = QSlider(self.centralwidget)
        self.IN_EQ.setObjectName(u"IN_EQ")
        self.IN_EQ.setGeometry(QRect(50, 70, 10, 101))
        self.IN_EQ.setTabletTracking(True)
        self.IN_EQ.setFocusPolicy(Qt.ClickFocus)
        self.IN_EQ.setToolTipDuration(-1)
        self.IN_EQ.setLayoutDirection(Qt.RightToLeft)
        self.IN_EQ.setLocale(QLocale(QLocale.English, QLocale.UnitedKingdom))
        self.IN_EQ.setMinimum(0)
        self.IN_EQ.setMaximum(30)
        self.IN_EQ.setOrientation(Qt.Vertical)
        self.IN_EQ.setInvertedAppearance(False)
        self.IN_EQ.setInvertedControls(False)
        self.OUT_EQ_T = QLabel(self.centralwidget)
        self.OUT_EQ_T.setObjectName(u"OUT_EQ_T")
        # self.OUT_EQ_T.setGeometry(QRect(560, 180, 51, 31))
        self.OUT_EQ_T.setGeometry(QRect(500, 180, 51, 31))
        self.OUT_EQ_T.setFocusPolicy(Qt.NoFocus)
        self.OUT_EQ_T.setLocale(QLocale(QLocale.English, QLocale.UnitedKingdom))
        self.OUT_EQ_T.setAlignment(Qt.AlignCenter)
        self.OUT_EQ_T.setWordWrap(True)
        self.OUT_EQ_L = QLabel(self.centralwidget)
        self.OUT_EQ_L.setObjectName(u"OUT_EQ_L")
        # self.OUT_EQ_L.setGeometry(QRect(550, 50, 71, 16))
        self.OUT_EQ_L.setGeometry(QRect(490, 50, 71, 16))
        self.OUT_EQ_L.setFocusPolicy(Qt.NoFocus)
        self.OUT_EQ_L.setLocale(QLocale(QLocale.English, QLocale.UnitedKingdom))
        self.OUT_EQ_L.setAlignment(Qt.AlignCenter)
        self.OUT_EQ = QSlider(self.centralwidget)
        self.OUT_EQ.setObjectName(u"OUT_EQ")
        # self.OUT_EQ.setGeometry(QRect(580, 70, 10, 101))
        self.OUT_EQ.setGeometry(QRect(520, 70, 10, 101))
        self.OUT_EQ.setTabletTracking(True)
        self.OUT_EQ.setFocusPolicy(Qt.ClickFocus)
        self.OUT_EQ.setLocale(QLocale(QLocale.English, QLocale.UnitedKingdom))
        self.OUT_EQ.setMinimum(0)
        self.OUT_EQ.setMaximum(30)
        self.OUT_EQ.setOrientation(Qt.Vertical)
        self.OUT_EQ.setInvertedAppearance(False)
        self.OUT_EQ.setInvertedControls(False)
        self.MOD_SOURCE = QComboBox(self.centralwidget)
        self.MOD_SOURCE.addItem("")
        self.MOD_SOURCE.addItem("")
        self.MOD_SOURCE.addItem("")
        self.MOD_SOURCE.addItem("")
        self.MOD_SOURCE.addItem("")
        self.MOD_SOURCE.addItem("")
        self.MOD_SOURCE.addItem("")
        self.MOD_SOURCE.addItem("")
        self.MOD_SOURCE.setObjectName(u"MOD_SOURCE")
        self.MOD_SOURCE.setGeometry(QRect(614, 70, 161, 32))
        self.MOD_SOURCE.setTabletTracking(True)
        self.MOD_SOURCE.setFocusPolicy(Qt.ClickFocus)
        self.MOD_SOURCE.setLocale(QLocale(QLocale.English, QLocale.UnitedKingdom))
        self.MOD_DEST = QComboBox(self.centralwidget)
        self.MOD_DEST.addItem("")
        self.MOD_DEST.addItem("")
        self.MOD_DEST.addItem("")
        self.MOD_DEST.addItem("")
        self.MOD_DEST.addItem("")
        self.MOD_DEST.addItem("")
        self.MOD_DEST.addItem("")
        self.MOD_DEST.setObjectName(u"MOD_DEST")
        self.MOD_DEST.setGeometry(QRect(614, 110, 161, 32))
        self.MOD_DEST.setTabletTracking(True)
        self.MOD_DEST.setFocusPolicy(Qt.ClickFocus)
        self.MOD_DEST.setLocale(QLocale(QLocale.English, QLocale.UnitedKingdom))
        self.CHORUS_T = QLabel(self.centralwidget)
        self.CHORUS_T.setObjectName(u"CHORUS_T")
        self.CHORUS_T.setGeometry(QRect(80, 6, 181, 40))
        self.CHORUS_T.setFocusPolicy(Qt.NoFocus)
        self.CHORUS_T.setLocale(QLocale(QLocale.English, QLocale.UnitedKingdom))
        self.CHORUS_T.setAlignment(Qt.AlignCenter)
        self.CHORUS_T.setWordWrap(True)
        self.DLY_T = QLabel(self.centralwidget)
        self.DLY_T.setObjectName(u"DLY_T")
        self.DLY_T.setGeometry(QRect(257, 10, 181, 31))
        self.DLY_T.setFocusPolicy(Qt.NoFocus)
        self.DLY_T.setLocale(QLocale(QLocale.English, QLocale.UnitedKingdom))
        self.DLY_T.setAlignment(Qt.AlignCenter)
        self.DLY_T.setWordWrap(True)
        self.REV_T = QLabel(self.centralwidget)
        self.REV_T.setObjectName(u"REV_T")
        self.REV_T.setGeometry(QRect(440, 10, 170, 31))
        self.REV_T.setFocusPolicy(Qt.NoFocus)
        self.REV_T.setLocale(QLocale(QLocale.English, QLocale.UnitedKingdom))
        self.REV_T.setAlignment(Qt.AlignCenter)
        self.REV_T.setWordWrap(True)
        self.MOD_T = QLabel(self.centralwidget)
        self.MOD_T.setObjectName(u"MOD_T")
        self.MOD_T.setGeometry(QRect(610, 10, 181, 31))
        self.MOD_T.setFocusPolicy(Qt.NoFocus)
        self.MOD_T.setLocale(QLocale(QLocale.English, QLocale.UnitedKingdom))
        self.MOD_T.setAlignment(Qt.AlignCenter)
        self.MOD_T.setWordWrap(True)
        self.MOD_AMT = QSlider(self.centralwidget)
        self.MOD_AMT.setObjectName(u"MOD_AMT")
        self.MOD_AMT.setGeometry(QRect(624, 158, 141, 10))
        self.MOD_AMT.setTabletTracking(True)
        self.MOD_AMT.setFocusPolicy(Qt.ClickFocus)
        self.MOD_AMT.setLocale(QLocale(QLocale.English, QLocale.UnitedKingdom))
        self.MOD_AMT.setMaximum(198)
        self.MOD_AMT.setOrientation(Qt.Horizontal)
        self.MOD_AMT.setInvertedAppearance(False)
        self.MOD_AMT.setInvertedControls(False)
        self.MOD_AMT_L = QLabel(self.centralwidget)
        self.MOD_AMT_L.setObjectName(u"MOD_AMT_L")
        self.MOD_AMT_L.setGeometry(QRect(656, 180, 71, 16))
        self.MOD_AMT_L.setFocusPolicy(Qt.NoFocus)
        self.MOD_AMT_L.setLocale(QLocale(QLocale.English, QLocale.UnitedKingdom))
        self.MOD_AMT_L.setAlignment(Qt.AlignCenter)
        self.CHRS_SPEED = QSlider(self.centralwidget)
        self.CHRS_SPEED.setObjectName(u"CHRS_SPEED")
        self.CHRS_SPEED.setGeometry(QRect(110, 150, 121, 10))
        self.CHRS_SPEED.setTabletTracking(True)
        self.CHRS_SPEED.setFocusPolicy(Qt.ClickFocus)
        self.CHRS_SPEED.setLocale(QLocale(QLocale.English, QLocale.UnitedKingdom))
        self.CHRS_SPEED.setOrientation(Qt.Horizontal)
        self.CHRS_SPEED.setInvertedAppearance(False)
        self.CHRS_SPEED.setInvertedControls(False)
        self.CHRS_SPEED_L = QLabel(self.centralwidget)
        self.CHRS_SPEED_L.setObjectName(u"CHRS_SPEED_L")
        self.CHRS_SPEED_L.setGeometry(QRect(130, 170, 71, 16))
        self.CHRS_SPEED_L.setFocusPolicy(Qt.ClickFocus)
        self.CHRS_SPEED_L.setLocale(QLocale(QLocale.English, QLocale.UnitedKingdom))
        self.CHRS_SPEED_L.setAlignment(Qt.AlignCenter)
        self.PROG_T_2 = QLabel(self.centralwidget)
        self.PROG_T_2.setObjectName(u"PROG_T_2")
        self.PROG_T_2.setGeometry(QRect(443, 226, 91, 16))
        self.PROG_T_2.setFocusPolicy(Qt.NoFocus)
        self.PROG_T_2.setLocale(QLocale(QLocale.English, QLocale.UnitedKingdom))
        self.PROG_T_3 = QLabel(self.centralwidget)
        self.PROG_T_3.setObjectName(u"PROG_T_3")
        self.PROG_T_3.setGeometry(QRect(20, 226, 91, 16))
        self.PROG_T_3.setFocusPolicy(Qt.NoFocus)
        self.PROG_T_3.setLocale(QLocale(QLocale.English, QLocale.UnitedKingdom))
        self.BANK_PATH = QLabel(self.centralwidget)
        self.BANK_PATH.setObjectName(u"BANK_PATH")
        self.BANK_PATH.setGeometry(QRect(20, 259, 451, 31))
        self.BANK_PATH.setFocusPolicy(Qt.NoFocus)
        self.BANK_PATH.setLocale(QLocale(QLocale.English, QLocale.UnitedKingdom))
        self.BANK_PATH.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.BANK_PATH.setWordWrap(True)
        self.PROGRAM_ID = QSpinBox(self.centralwidget)
        self.PROGRAM_ID.setObjectName(u"PROGRAM_ID")
        self.PROGRAM_ID.setGeometry(QRect(500, 267, 41, 21))
        self.PROGRAM_ID.setMinimum(100)
        self.PROGRAM_ID.setMaximum(199)
        self.PROG_RECALL = QPushButton(self.centralwidget)
        self.PROG_RECALL.setObjectName(u"PROG_RECALL")
        self.PROG_RECALL.setGeometry(QRect(670, 260, 91, 32))
        self.PROG_SYNC = QPushButton(self.centralwidget)
        self.PROG_SYNC.setObjectName(u"PROG_SYNC")
        self.PROG_SYNC.setGeometry(QRect(570, 260, 91, 32))
        UIMainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(UIMainWindow)
        self.statusbar.setObjectName(u"statusbar")
        UIMainWindow.setStatusBar(self.statusbar)
        self.menubar = QMenuBar(UIMainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 800, 37))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuDevice = QMenu(self.menubar)
        self.menuDevice.setObjectName(u"menuDevice")
        UIMainWindow.setMenuBar(self.menubar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuDevice.menuAction())
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionImport)
        self.menuFile.addAction(self.actionBankSave)
        self.menuFile.addAction(self.actionBankExport)
        self.menuFile.addAction(self.actionBufferExport)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSettings)
        self.menuFile.addAction(self.actionHelp)
        self.menuFile.addAction(self.actionAbout)
        self.menuFile.addAction(self.actionQuit)
        self.menuDevice.addSeparator()
        self.menuDevice.addAction(self.actionStoreProgram)
        self.menuDevice.addAction(self.actionDeviceStoreBank)
        self.menuDevice.addAction(self.actionDeviceRequestBank)

        self.retranslateUi(UIMainWindow)

        QMetaObject.connectSlotsByName(UIMainWindow)
    # setupUi

    def retranslateUi(self, UIMainWindow):
        UIMainWindow.setWindowTitle(QCoreApplication.translate("UIMainWindow", u"Midiverb III", None))
        self.actionSettings.setText(QCoreApplication.translate("UIMainWindow", u"Settings", None))
        self.actionQuit.setText(QCoreApplication.translate("UIMainWindow", u"Quit", None))
#if QT_CONFIG(shortcut)
        self.actionQuit.setShortcut(QCoreApplication.translate("UIMainWindow", u"Ctrl+Q", None))
#endif // QT_CONFIG(shortcut)
        self.actionImport.setText(QCoreApplication.translate("UIMainWindow", u"Open", None))
#if QT_CONFIG(tooltip)
        self.actionBufferExport.setText(QCoreApplication.translate("UIMainWindow", u"Save Program", None))
# if QT_CONFIG(shortcut)
        self.actionBufferExport.setShortcut(QCoreApplication.translate("UIMainWindow", u"Ctrl+X", None))
        self.actionImport.setToolTip(QCoreApplication.translate("UIMainWindow", u"Import a bank or a program", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionImport.setShortcut(QCoreApplication.translate("UIMainWindow", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.actionBankExport.setText(QCoreApplication.translate("UIMainWindow", u"Save Bank As", None))
#if QT_CONFIG(tooltip)
        self.actionBankExport.setToolTip(QCoreApplication.translate("UIMainWindow", u"Save the bank into a syx file", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionBankExport.setShortcut(QCoreApplication.translate("UIMainWindow", u"Ctrl+Shift+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionBankSave.setText(QCoreApplication.translate("UIMainWindow", u"Save Bank", None))
#if QT_CONFIG(tooltip)
        self.actionBankSave.setToolTip(QCoreApplication.translate("UIMainWindow", u"Save the current bank data", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionBankSave.setShortcut(QCoreApplication.translate("UIMainWindow", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionAbout.setText(QCoreApplication.translate("UIMainWindow", u"About", None))
#endif // QT_CONFIG(shortcut)
        self.actionNew.setText(QCoreApplication.translate("UIMainWindow", u"New Bank", None))
#if QT_CONFIG(tooltip)
        self.actionNew.setToolTip(QCoreApplication.translate("UIMainWindow", u"Create a new bank from the template", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionNew.setShortcut(QCoreApplication.translate("UIMainWindow", u"Ctrl+N", None))
#endif // QT_CONFIG(shortcut)
        self.actionStoreProgram.setText(QCoreApplication.translate("UIMainWindow", u"Store Program", None))
#if QT_CONFIG(tooltip)
        self.actionStoreProgram.setToolTip(QCoreApplication.translate("UIMainWindow", u"Save the current buffer to the device and save it in the selected slot", None))
#endif // QT_CONFIG(tooltip)
        self.actionDeviceStoreBank.setText(QCoreApplication.translate("UIMainWindow", u"Store Bank", None))
#if QT_CONFIG(tooltip)
        self.actionDeviceStoreBank.setToolTip(QCoreApplication.translate("UIMainWindow", u"Send the whole bank to the device (may take up to 10 sec)", None))
#endif // QT_CONFIG(tooltip)
        self.actionHelp.setText(QCoreApplication.translate("UIMainWindow", u"Help", None))
        self.actionDeviceRequestBank.setText(QCoreApplication.translate("UIMainWindow", u"Request Bank", None))
#if QT_CONFIG(tooltip)
        self.actionDeviceRequestBank.setToolTip(QCoreApplication.translate("UIMainWindow", u"Request a bank dump from the device and overwrite the current bank (may take up to 10 sec)", None))
#endif // QT_CONFIG(tooltip)
        self.CONFIGURATION.setItemText(0, QCoreApplication.translate("UIMainWindow", u"(EQ) > CHS > DLY > REV", None))
        self.CONFIGURATION.setItemText(1, QCoreApplication.translate("UIMainWindow", u"(EQ) > CHS > DLY   |   (EQ) > CHS > REV", None))
        self.CONFIGURATION.setItemText(2, QCoreApplication.translate("UIMainWindow", u"(EQ) > CHS > REV   |   DLY", None))
        self.CONFIGURATION.setItemText(3, QCoreApplication.translate("UIMainWindow", u"(EQ) > CHS > REV   |   (EQ) > DLY", None))
        self.CONFIGURATION.setItemText(4, QCoreApplication.translate("UIMainWindow", u"(EQ) > REV   |   CHS > DLY", None))
        self.CONFIGURATION.setItemText(5, QCoreApplication.translate("UIMainWindow", u"(EQ) > DLY   |   CHS > REV", None))
        self.CONFIGURATION.setItemText(6, QCoreApplication.translate("UIMainWindow", u"(EQ) > (CHS) > DLY > REV", None))
        self.CONFIGURATION.setItemText(7, QCoreApplication.translate("UIMainWindow", u"(EQ) > (CHS) > DLY   |   (EQ) > (CHS) > REV", None))
        self.CONFIGURATION.setItemText(8, QCoreApplication.translate("UIMainWindow", u"(EQ) > (CHS) > REV   |   DLY", None))
        self.CONFIGURATION.setItemText(9, QCoreApplication.translate("UIMainWindow", u"(EQ) > (CHS) > REV   |   (EQ) > DLY", None))
        self.CONFIGURATION.setItemText(10, QCoreApplication.translate("UIMainWindow", u"(EQ) > REV   |   (CHS) > DLY", None))
        self.CONFIGURATION.setItemText(11, QCoreApplication.translate("UIMainWindow", u"(EQ) > DLY   |   (CHS) > REV", None))
        self.CONFIGURATION.setItemText(12, QCoreApplication.translate("UIMainWindow", u"(EQ) > DLY > REV   |   CHS", None))
        self.CONFIGURATION.setItemText(13, QCoreApplication.translate("UIMainWindow", u"(EQ) > CHS > XDLY", None))
        self.CONFIGURATION.setItemText(14, QCoreApplication.translate("UIMainWindow", u"(EQ) > (CHS) > XDLY", None))

#if QT_CONFIG(tooltip)
        self.CONFIGURATION.setToolTip(QCoreApplication.translate("UIMainWindow", u"Choose internal signal routing, > - direction | - parallel routing (...) - not present in the output", None))
#endif // QT_CONFIG(tooltip)
        self.CHRS_TYPE.setItemText(0, QCoreApplication.translate("UIMainWindow", u"CHORUS XS", None))
        self.CHRS_TYPE.setItemText(1, QCoreApplication.translate("UIMainWindow", u"CHORUS S", None))
        self.CHRS_TYPE.setItemText(2, QCoreApplication.translate("UIMainWindow", u"CHORUS M", None))
        self.CHRS_TYPE.setItemText(3, QCoreApplication.translate("UIMainWindow", u"CHORUS XM", None))
        self.CHRS_TYPE.setItemText(4, QCoreApplication.translate("UIMainWindow", u"CHORUS L", None))
        self.CHRS_TYPE.setItemText(5, QCoreApplication.translate("UIMainWindow", u"CHORUS XL", None))
        self.CHRS_TYPE.setItemText(6, QCoreApplication.translate("UIMainWindow", u"FLANGER XS", None))
        self.CHRS_TYPE.setItemText(7, QCoreApplication.translate("UIMainWindow", u"FLANGER S", None))
        self.CHRS_TYPE.setItemText(8, QCoreApplication.translate("UIMainWindow", u"FLANGER M", None))
        self.CHRS_TYPE.setItemText(9, QCoreApplication.translate("UIMainWindow", u"FLANGER XM", None))
        self.CHRS_TYPE.setItemText(10, QCoreApplication.translate("UIMainWindow", u"FLANGER L", None))
        self.CHRS_TYPE.setItemText(11, QCoreApplication.translate("UIMainWindow", u"FLANGER XL", None))

#if QT_CONFIG(tooltip)
        self.CHRS_TYPE.setToolTip(QCoreApplication.translate("UIMainWindow", u"Pitch FX types: choruses and flangers, the sizes mean the depth of effect", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.CHRS_STEREO.setToolTip(QCoreApplication.translate("UIMainWindow", u"Switch between mono and stereo", None))
#endif // QT_CONFIG(tooltip)
        self.CHRS_STEREO.setText(QCoreApplication.translate("UIMainWindow", u"Stereo", None))
#if QT_CONFIG(tooltip)
        self.DLY_TIME_T.setToolTip(QCoreApplication.translate("UIMainWindow", u"Delay time in ms, note that for DLY the maximum is 100ms, for XDLY — 400ms", None))
#endif // QT_CONFIG(tooltip)
        self.DLY_TIME_T.setText(QCoreApplication.translate("UIMainWindow", u"Time", None))
#if QT_CONFIG(tooltip)
        self.DLY_TIME.setToolTip(QCoreApplication.translate("UIMainWindow", u"Delay time in ms, note that for DLY the maximum is 100ms, for XDLY — 400ms", None))
#endif // QT_CONFIG(tooltip)
        self.DLY_TIME_L.setText(QCoreApplication.translate("UIMainWindow", u"+0", None))
#if QT_CONFIG(tooltip)
        self.REV_MIX_T.setToolTip(QCoreApplication.translate("UIMainWindow", u"Reverb level", None))
#endif // QT_CONFIG(tooltip)
        self.REV_MIX_T.setText(QCoreApplication.translate("UIMainWindow", u"Level", None))
        self.REV_MIX_L.setText(QCoreApplication.translate("UIMainWindow", u"+0", None))
#if QT_CONFIG(tooltip)
        self.REV_MIX.setToolTip(QCoreApplication.translate("UIMainWindow", u"Reverb level", None))
#endif // QT_CONFIG(tooltip)
        self.DLY_REGEN_L.setText(QCoreApplication.translate("UIMainWindow", u"+0", None))
        self.DLY_REGEN_T.setText(QCoreApplication.translate("UIMainWindow", u"Regen", None))
#if QT_CONFIG(tooltip)
        self.DLY_REGEN.setToolTip(QCoreApplication.translate("UIMainWindow", u"Delay feedback amount", None))
#endif // QT_CONFIG(tooltip)
        self.REV_DECAY_L.setText(QCoreApplication.translate("UIMainWindow", u"+0", None))
#if QT_CONFIG(tooltip)
        self.REV_DECAY.setToolTip(QCoreApplication.translate("UIMainWindow", u"Reverb decay amount", None))
#endif // QT_CONFIG(tooltip)
        self.REV_DECAY_T.setText(QCoreApplication.translate("UIMainWindow", u"Decay", None))
        self.DLY_MIX_T.setText(QCoreApplication.translate("UIMainWindow", u"Level", None))
        self.DLY_MIX_L.setText(QCoreApplication.translate("UIMainWindow", u"+0", None))
#if QT_CONFIG(tooltip)
        self.DLY_MIX.setToolTip(QCoreApplication.translate("UIMainWindow", u"Delay output level", None))
#endif // QT_CONFIG(tooltip)
        self.REVERB_TYPE.setItemText(0, QCoreApplication.translate("UIMainWindow", u"SMALL ROOM", None))
        self.REVERB_TYPE.setItemText(1, QCoreApplication.translate("UIMainWindow", u"SMALL ROOM DIFF", None))
        self.REVERB_TYPE.setItemText(2, QCoreApplication.translate("UIMainWindow", u"MEDIUM ROOM", None))
        self.REVERB_TYPE.setItemText(3, QCoreApplication.translate("UIMainWindow", u"LARGE ROOM", None))
        self.REVERB_TYPE.setItemText(4, QCoreApplication.translate("UIMainWindow", u"SMALL HALL", None))
        self.REVERB_TYPE.setItemText(5, QCoreApplication.translate("UIMainWindow", u"SMALL HALL DIFF", None))
        self.REVERB_TYPE.setItemText(6, QCoreApplication.translate("UIMainWindow", u"MEDIUM HALL", None))
        self.REVERB_TYPE.setItemText(7, QCoreApplication.translate("UIMainWindow", u"LARGE HALL", None))
        self.REVERB_TYPE.setItemText(8, QCoreApplication.translate("UIMainWindow", u"MEDIUM CHAMBER", None))
        self.REVERB_TYPE.setItemText(9, QCoreApplication.translate("UIMainWindow", u"MEDIUM CHAMBER DIFF", None))
        self.REVERB_TYPE.setItemText(10, QCoreApplication.translate("UIMainWindow", u"LARGE CHAMBER", None))
        self.REVERB_TYPE.setItemText(11, QCoreApplication.translate("UIMainWindow", u"PERC CHAMBER", None))
        self.REVERB_TYPE.setItemText(12, QCoreApplication.translate("UIMainWindow", u"PERC PLATE", None))
        self.REVERB_TYPE.setItemText(13, QCoreApplication.translate("UIMainWindow", u"TIGHT PLATE", None))
        self.REVERB_TYPE.setItemText(14, QCoreApplication.translate("UIMainWindow", u"SOFT PLATE", None))
        self.REVERB_TYPE.setItemText(15, QCoreApplication.translate("UIMainWindow", u"VOCAL PLATE", None))
        self.REVERB_TYPE.setItemText(16, QCoreApplication.translate("UIMainWindow", u"BRIGHT GATE", None))
        self.REVERB_TYPE.setItemText(17, QCoreApplication.translate("UIMainWindow", u"POWER GATE", None))
        self.REVERB_TYPE.setItemText(18, QCoreApplication.translate("UIMainWindow", u"MEDIUM REVERSE", None))
        self.REVERB_TYPE.setItemText(19, QCoreApplication.translate("UIMainWindow", u"SLOW REVERSE", None))

#if QT_CONFIG(tooltip)
        self.REVERB_TYPE.setToolTip(QCoreApplication.translate("UIMainWindow", u"Reverb algorithms", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.IN_EQ_T.setToolTip(QCoreApplication.translate("UIMainWindow", u"Input signal 3db lowpass filter", None))
#endif // QT_CONFIG(tooltip)
        self.IN_EQ_T.setText(QCoreApplication.translate("UIMainWindow", u"EQ", None))
        self.IN_EQ_L.setText(QCoreApplication.translate("UIMainWindow", u"+0", None))
#if QT_CONFIG(tooltip)
        self.IN_EQ.setToolTip(QCoreApplication.translate("UIMainWindow", u"Input signal 3db lowpass filter", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.OUT_EQ_T.setToolTip(QCoreApplication.translate("UIMainWindow", u"Feedback lowpass filter", None))
#endif // QT_CONFIG(tooltip)
        self.OUT_EQ_T.setText(QCoreApplication.translate("UIMainWindow", u"Tone", None))
        self.OUT_EQ_L.setText(QCoreApplication.translate("UIMainWindow", u"+0", None))
#if QT_CONFIG(tooltip)
        self.OUT_EQ.setToolTip(QCoreApplication.translate("UIMainWindow", u"Feedback lowpass filter", None))
#endif // QT_CONFIG(tooltip)
        self.MOD_SOURCE.setItemText(0, QCoreApplication.translate("UIMainWindow", u"VOLUME (CC7)", None))
        self.MOD_SOURCE.setItemText(1, QCoreApplication.translate("UIMainWindow", u"PITCH BEND", None))
        self.MOD_SOURCE.setItemText(2, QCoreApplication.translate("UIMainWindow", u"MOD WHEEL (CC1)", None))
        self.MOD_SOURCE.setItemText(3, QCoreApplication.translate("UIMainWindow", u"NOTE NUMBER", None))
        self.MOD_SOURCE.setItemText(4, QCoreApplication.translate("UIMainWindow", u"VELOCITY", None))
        self.MOD_SOURCE.setItemText(5, QCoreApplication.translate("UIMainWindow", u"AFTERTOUCH", None))
        self.MOD_SOURCE.setItemText(6, QCoreApplication.translate("UIMainWindow", u"SUSTAIN PEDAL (CC64)", None))
        self.MOD_SOURCE.setItemText(7, QCoreApplication.translate("UIMainWindow", u"BREATH", None))

#if QT_CONFIG(tooltip)
        self.MOD_SOURCE.setToolTip(QCoreApplication.translate("UIMainWindow", u"Modulation source (only one allowed)", None))
#endif // QT_CONFIG(tooltip)
        self.MOD_DEST.setItemText(0, QCoreApplication.translate("UIMainWindow", u"OFF", None))
        self.MOD_DEST.setItemText(1, QCoreApplication.translate("UIMainWindow", u"REV DECAY", None))
        self.MOD_DEST.setItemText(2, QCoreApplication.translate("UIMainWindow", u"DLY TIME", None))
        self.MOD_DEST.setItemText(3, QCoreApplication.translate("UIMainWindow", u"DLY REGEN", None))
        self.MOD_DEST.setItemText(4, QCoreApplication.translate("UIMainWindow", u"CHRS SPEED", None))
        self.MOD_DEST.setItemText(5, QCoreApplication.translate("UIMainWindow", u"REV LEVEL", None))
        self.MOD_DEST.setItemText(6, QCoreApplication.translate("UIMainWindow", u"DLY LEVEl", None))

#if QT_CONFIG(tooltip)
        self.MOD_DEST.setToolTip(QCoreApplication.translate("UIMainWindow", u"Modulation destination (only one allowed)", None))
#endif // QT_CONFIG(tooltip)
        self.CHORUS_T.setText(QCoreApplication.translate("UIMainWindow", u"CHORUS", None))
        self.DLY_T.setText(QCoreApplication.translate("UIMainWindow", u"DELAY", None))
        self.REV_T.setText(QCoreApplication.translate("UIMainWindow", u"REVERB", None))
        self.MOD_T.setText(QCoreApplication.translate("UIMainWindow", u"MODULATION", None))
#if QT_CONFIG(tooltip)
        self.MOD_AMT.setToolTip(QCoreApplication.translate("UIMainWindow", u"Modulation depth", None))
#endif // QT_CONFIG(tooltip)
        self.MOD_AMT_L.setText(QCoreApplication.translate("UIMainWindow", u"+0", None))
#if QT_CONFIG(tooltip)
        self.CHRS_SPEED.setToolTip(QCoreApplication.translate("UIMainWindow", u"Chorus / flanger speed", None))
#endif // QT_CONFIG(tooltip)
        self.CHRS_SPEED_L.setText(QCoreApplication.translate("UIMainWindow", u"+0", None))
#if QT_CONFIG(tooltip)
        self.PROG_T_2.setToolTip(QCoreApplication.translate("UIMainWindow", u"Reverb algorithms", None))
#endif // QT_CONFIG(tooltip)
        self.PROG_T_2.setText(QCoreApplication.translate("UIMainWindow", u"ALGORITHM", None))
#if QT_CONFIG(tooltip)
        self.PROG_T_3.setToolTip(QCoreApplication.translate("UIMainWindow", u"Choose routing, there are some parallel and some sequential algorithms, note that some fx blocks may be disabled for some algorithms", None))
#endif // QT_CONFIG(tooltip)
        self.PROG_T_3.setText(QCoreApplication.translate("UIMainWindow", u"ROUTING", None))
#if QT_CONFIG(tooltip)
        self.BANK_PATH.setToolTip(QCoreApplication.translate("UIMainWindow", u"Loaded bank path", None))
#endif // QT_CONFIG(tooltip)
        self.BANK_PATH.setText(QCoreApplication.translate("UIMainWindow", u"DEFAULT BANK", None))
#if QT_CONFIG(tooltip)
        self.PROG_RECALL.setToolTip(QCoreApplication.translate("UIMainWindow", u"Discard the buffer and recall the stored program", None))
#endif // QT_CONFIG(tooltip)
        self.PROG_RECALL.setText(QCoreApplication.translate("UIMainWindow", u"RECALL", None))
#if QT_CONFIG(tooltip)
        self.PROG_SYNC.setToolTip(QCoreApplication.translate("UIMainWindow", u"Send current UI settings to the device buffer (this won't save it to the memory slot)", None))
#endif // QT_CONFIG(tooltip)
        self.PROG_SYNC.setText(QCoreApplication.translate("UIMainWindow", u"SYNC", None))
        self.menuFile.setTitle(QCoreApplication.translate("UIMainWindow", u"File", None))
        self.menuDevice.setTitle(QCoreApplication.translate("UIMainWindow", u"Device", None))
    # retranslateUi

